services:
  postgres:
    container_name: postgres-game-store-app
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: game_store_app_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"




volumes:
  postgres:
    driver: local